### ISSUE TITLE
Usage with Ractors causes a segmentation fault

### ISSUE THREAD

**Issue by michaelherold** [SamSaffron/memory_profiler#112]
When using memory_profiler with Ractors, it causes a segfault in (I believe) `gc_event_hook_body`. I'm unsure if that's a VM issue or something in the library code, but I have a minimal reproduction that came from michaelherold/benchmark-memory#27:

```ruby
# frozen_string_literal: true

require "memory_profiler"

def factorial(n)
  n == 0 ? 1 : n * factorial(n - 1)
end

MemoryProfiler.start

ractor = Ractor.new do
  1000.times { factorial(1000) }
end

# take response from ractor, so it will actually execute
ractor.take

MemoryProfiler.stop.pretty_print
```

Running on 3.2.2 causes a segfault. When you don't call `Ractor#take` to execute it, there is no segfault.

I thought you'd want to know!

**Comment by SamSaffron** [comment]
Can you raise on ruby bug tracker?

**Comment by michaelherold** [comment]
No need for a new bug because it [was already reported](https://bugs.ruby-lang.org/issues/18464) and [fixed](https://github.com/ruby/ruby/pull/5990) for the upcoming 3.3 release. I verified this on the latest commit of Ruby's trunk.

It [was back ported](https://github.com/ruby/ruby/commit/b422c3523c419b88c6da23a4022ae8864f411b84) for 3.2 as well, but would be out in a 3.2.3 release, which has not yet been released.

There is a backport for 3.1 as well, which I assume is in the same state.

All that to say that this should not be a problem in Rubies newer than the ones out today.

I will go ahead and close this since people looking for an answer here can find this thread via search.
