### ISSUE TITLE
Feature request: ability to profile commands

### ISSUE THREAD

**Issue by fatkodima** [SamSaffron/memory_profiler#113]
Currently, CLI is able to profile only single ruby files via `memory-profiler ruby_file.rb` (we pass a file name and the gem loads it and profiles the memory).
It will be very convenient to be able to profile whole commands/processes, like `rspec`, `rails` etc via something like 
`memory-profiler run ...gem options... -- rails test ...command options...`.

The interface will like the one added for `stackprof` (https://github.com/tmm1/stackprof/pull/187).

If this is OK, I can open a PR.

**Comment by SamSaffron** [comment]
seems fine to me , sure give it a shot
