### ISSUE TITLE
How to optimize module names as allocated strings

### ISSUE THREAD

**Issue by jmthomas** [SamSaffron/memory_profiler#13]
I'm profiling [COSMOS](https://github.com/BallAerospace/COSMOS) which is a [qtbindings](https://github.com/ryanmelt/qtbindings/) application. My highest allocated string report is 'Qt' because it's how everything is namespaced. Is there anyway to optimize this? Thanks for an awesome gem!

**Comment by SamSaffron** [comment]
Quite a few ways... 

Under 2.1-2.2 

change "Qt" in code to "Qt".freeze, under 2.0 and below define a constant. 

Have a look at where the actual allocations are coming from.

**Comment by jmthomas** [comment]
But I'm not actually using the string 'Qt', I'm using classes like Qt::TextEdit for example. Actually now that I think about it, this could be die to the way the qtbindings gem does the dynamic method dispatching.
