### ISSUE TITLE
How to intrepret the results and get the memory size

### ISSUE THREAD

**Issue by khelll** [SamSaffron/memory_profiler#15]
Excuse my ignorance here, but as I can tell, the numbers here represent the objects created. I understand this is helpful specially when tracing memory leaks by checking the increased number of objects. However, is there a way where I can convert this number to real memory size consumed by the profiled code? 
Right now I'm doing this to get it in Mbs, but for the whole running process:
```ruby
# (number of heaps * size of a heap * size of an object in bytes) / bytes per mb
(GC.stat[:heap_length] * GC::INTERNAL_CONSTANTS[:HEAP_OBJ_LIMIT] * GC::INTERNAL_CONSTANTS[:RVALUE_SIZE]) / 1024 ** 2
```

**Comment by dgynn** [comment]
@khelll The latest version of the gem now reports on memory size as well as objects created. At the end of profiling `ObjectSpace.memsize_of(obj)` is called for each object that was allocated to get the actual size.
