### ISSUE TITLE
Integration with rack-mini-profiler

### ISSUE THREAD

**Issue by brauliobo** [SamSaffron/memory_profiler#22]
Can this profile memory of requests and theirs parts (SQL queries, etc) and output the result in the `rack-mini-profiler` HTML?

**Comment by SamSaffron** [comment]
We would need to build an integration piece but I am not against it if you
wanted to work on it.

**Comment by nateberkopec** [comment]
@SamSaffron I believe this is done now, no?

**Comment by SamSaffron** [comment]
Yes, this is now done, there is an option under pp=help
