### ISSUE TITLE
undefined method `name' in 0.9.5

### ISSUE THREAD

**Issue by vincentwoo** [SamSaffron/memory_profiler#27]
When trying to profile some stuff, I get:

```
NoMethodError: undefined method `name' for nil:NilClass
/Users/vwoo/.gem/ruby/2.2.3/gems/memory_profiler-0.9.5/lib/memory_profiler/helpers.rb:28:in `lookup_class_name'
/Users/vwoo/.gem/ruby/2.2.3/gems/memory_profiler-0.9.5/lib/memory_profiler/reporter.rb:100:in `block in object_list'
/Users/vwoo/.gem/ruby/2.2.3/gems/memory_profiler-0.9.5/lib/memory_profiler/reporter.rb:92:in `each'
/Users/vwoo/.gem/ruby/2.2.3/gems/memory_profiler-0.9.5/lib/memory_profiler/reporter.rb:92:in `object_list'
/Users/vwoo/.gem/ruby/2.2.3/gems/memory_profiler-0.9.5/lib/memory_profiler/reporter.rb:40:in `run'
/Users/vwoo/.gem/ruby/2.2.3/gems/memory_profiler-0.9.5/lib/memory_profiler/reporter.rb:27:in `report'
/Users/vwoo/.gem/ruby/2.2.3/gems/memory_profiler-0.9.5/lib/memory_profiler.rb:14:in `report'
/Users/vwoo/coderpad.io/lib/tasks/stripe.rake:7:in `block in <top (required)>'
/Users/vwoo/.gem/ruby/2.2.3/gems/bugsnag-2.8.12/lib/bugsnag/rake.rb:12:in `execute_with_bugsnag'
Tasks: TOP => stripe
(See full trace by running task with --trace)
```

probably related to the new performance improvements. Checking for nil should probably do the trick.

https://github.com/SamSaffron/memory_profiler/blob/master/lib/memory_profiler/helpers.rb#L28

**Comment by dgynn** [comment]
Do you have any idea what the object was? I'm realizing now there will be an issue with BasicObjects that needs to be handled too. But that would be a different error.
What do you think was created that returned a `nil` for `.class()` ?

**Comment by vincentwoo** [comment]
I unfortunately do not have a good idea of that right now - I'm debugging code mostly in stripe-ruby land and I'm not an expert. I'm also not sure how I'd find out. If you give me detailed instructions on how to find that out, I'll try to dig for you.

**Comment by dgynn** [comment]
Could you temporarily add this line...
`puts "Found object with nil class #{ obj.inspect }" if klass.nil?`
to `memory_profiler/reporter.rb` right after the `obj.class` call on line 99?

**Comment by SamSaffron** [comment]
sure lets try this, probably a proxy or something ...

**Comment by dgynn** [comment]
Great. I've merged this fix and added handling for BasicObject too. It would be great if you could identify what the problem object was but at least we're preventing the issue now. Thanks!

**Comment by SamSaffron** [comment]
let me know when you want me to do a new gem release

**Comment by dgynn** [comment]
We probably should do one now. The pretty_print options issue is something that would be likely to occur. Thanks for doing that.

**Comment by SamSaffron** [comment]
Done ... just did a new release :)

**Comment by vincentwoo** [comment]
After some debugging, this appears to be something that `andand` does:

```
From: /Users/vwoo/.gem/ruby/2.2.3/gems/memory_profiler-0.9.6/lib/memory_profiler/reporter.rb @ line 100 MemoryProfiler::Reporter#object_list:

     95:         next if @allow_files && !(@allow_files =~ file)
     96:
     97:         line       = ObjectSpace.allocation_sourceline(obj)
     98:         location   = helper.lookup_location(file, line)
     99:         klass      = obj.class rescue nil
 => 100:         binding.pry if klass.nil?
    101:         class_name = helper.lookup_class_name(klass)
    102:         gem        = helper.guess_gem(file)
    103:         string     = '' << obj  if klass == String
    104:
    105:         begin

[1] pry(#<MemoryProfiler::Reporter>)> obj

[2] pry(#<MemoryProfiler::Reporter>)> obj.class
nil
[3] pry(#<MemoryProfiler::Reporter>)> obj.inspect.class
NilClass < Object
[4] pry(#<MemoryProfiler::Reporter>)> obj.nil?
nil
[5] pry(#<MemoryProfiler::Reporter>)> obj.class.nil?
true
[6] pry(#<MemoryProfiler::Reporter>)> obj.id
nil
[7] pry(#<MemoryProfiler::Reporter>)> file
"/Users/vwoo/.gem/ruby/2.2.3/gems/andand-1.3.3/lib/andand.rb"
[8] pry(#<MemoryProfiler::Reporter>)> line
36
```

Here's the relevant line: https://github.com/raganwald/andand/blob/master/lib/andand.rb#L36. Good luck!

**Comment by dgynn** [comment]
@vincentwoo Thanks for tracking that down. It looks like andand is doing some pretty hacky stuff to create its proxy object. That is a corner case I certainly never expected but I'm glad we're handling it now.
