### ISSUE TITLE
can't convert ItsIt::It to String

### ISSUE THREAD

**Issue by elsurudo** [SamSaffron/memory_profiler#34]
I'm trying to profile my gems in a Rails 2.2.5 app.

I've created `script/memory-profiler.rb` as follows:

```
require 'memory_profiler'

report = MemoryProfiler.report do
  require_relative '../config/environment'
  # Add specific code here if you want to profile deeper
end

report.pretty_print
```

`ruby script/memory-profiler.rb` gives me the following:

```
ernsputer:sign2web elsurudo$ ruby script/memory-profiler.rb 
/Users/elsurudo/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/memory_profiler-0.9.6/lib/memory_profiler/reporter.rb:102:in `block in object_list': can't convert ItsIt::It to String (ItsIt::It#to_str gives ItsIt::It) (TypeError)
	from /Users/elsurudo/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/memory_profiler-0.9.6/lib/memory_profiler/reporter.rb:92:in `each'
	from /Users/elsurudo/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/memory_profiler-0.9.6/lib/memory_profiler/reporter.rb:92:in `object_list'
	from /Users/elsurudo/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/memory_profiler-0.9.6/lib/memory_profiler/reporter.rb:40:in `run'
	from /Users/elsurudo/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/memory_profiler-0.9.6/lib/memory_profiler/reporter.rb:27:in `report'
	from /Users/elsurudo/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/memory_profiler-0.9.6/lib/memory_profiler.rb:14:in `report'
	from script/memory-profiler.rb:3:in `<main>'
```

Not sure how to proceed...

I am using memory_profiler (0.9.6).

Let me know if you need any more details about my environment.

**Comment by SamSaffron** [comment]
looks like a legit bug, we should get it fixed

**Comment by dgynn** [comment]
I don't see any way to get `memory_profiler` to work with `its-it`. From the docs...
> The it method creates an instance of the ItsIt::It class, which uses method_missing to capture and queue up all methods and their arguments except for :to_proc and :=== (and also excepting :respond_to? :to_proc and :respond_to? :===).

So, unfortunately, whenever an ItsIt::It object is allocated there is no way for `memory_profiler` to figure out anything about the object. It isn't possible to know that the object is an ItsIt::It class because `class` gets captured and queued.
```ruby
> an_it_object = it.to_s.size.to_s
=> #<ItsIt::It:0x3fe6c71da0cc>
> an_it_object.class
=> #<ItsIt::It:0x3fe6c71da0cc>
```

There are 2 ways you can work around this problem... First, you can just ignore the objects allocated by its-it using the `:ignore_files` option like...
```ruby
report = MemoryProfiler.report(:ignore_files=>'its-it') do
  # run your code here
end
```
Second, if you **do** want to profile its-it and you never are using its-it to defer calls to `class` you could modify the method to return a value rather than queuing the call...
```ruby
require 'its-it'
module ItsIt
  class It
    def class
      ItsIt::It
    end
  end
end
```

**Comment by SamSaffron** [comment]
Perhaps we can we catch the errors so they don't explode the whole
profiling run? (even report the errors as part of the report)

**Comment by dgynn** [comment]
Ah. Good point. It would be nice to not blow up too. I can fix that pretty quick.

We silently ignore errors in a few spots right now. It would be good to have some way to know about any of those.

**Comment by dgynn** [comment]
Fixed in eaf2c4c6 to prevent exceptions. Error reporting will be something to add later.

**Comment by SamSaffron** [comment]
awesome thanks!

**Comment by elsurudo** [comment]
Thanks for the quick help guys! Seems to be working now
