### ISSUE TITLE
Unclear usage options

### ISSUE THREAD

**Issue by MOZGIII** [SamSaffron/memory_profiler#45]
Could you please tell me (and add to the `README.md` if possible) whether it's safe to simultaneously have multiple `Reporter` instances and collect data using them?

In case it's allowed by design, is the code threadsafe? If I were to run it concurrently with `puma` - will it break?

**Comment by MOZGIII** [comment]
Checked out some code, and the readme-proposed interface would break if used concurrently, since `Reporter.current_reporter` is just an accessor. You could make it threadsafe by reimplementing it using `Thread.current['...']` to store the value.

However I'd like to measure object allocation across multiple threads, so that does not work for me either.
A little more info in the `README.md` on what to do this case you have to profile multiple threads would be useful.

**Comment by MOZGIII** [comment]
Read some more code. Yeah, this implementation can't work concurrently at all. Please document it.

**Comment by SamSaffron** [comment]
Multiple per-thread collectors working in concert is not something we ever even planned to build, not sure how feasible it is anyway given that  `ObjectSpace.trace_object_allocations_start` is not thread bound.

**Comment by MOZGIII** [comment]
Yeah, the problem is that GC and ObjectSpace are unique per process, and we're unable to work with them on a per-thread basis.

**Comment by MOZGIII** [comment]
I'm closing this. It would be useful to find a remark about all this in the readme.
