### ISSUE TITLE
Question about MemoryProfiler results

### ISSUE THREAD

**Issue by mariosouto** [SamSaffron/memory_profiler#53]
Hi,

I'm not having an actual issue with this gem, is just that i have a couple of questions to help me understand better the results that the gem gives me.

I'm using the gem to profile the memory in some parts of my code base, after profiling i get some results like

```
Total allocated: 6980019 bytes (75878 objects)
Total retained:  184943 bytes (943 objects)
```

- My first question is: being `943` the amount of total retained objects this actually means that i have a memory leak? Or it means something else? I'm not sure i completely understand this results.

- I get some results like

```
retained memory by location
-----------------------------------
     22288  /Users/msouto/Desktop/Test-App/app/models/person.rb:1
```

The line 1 of `person.rb` is the declaration of the class, specifically

```
class Person < ActiveRecord::Base
end
```

how do i intepret this? The class Person is leaking? Should i profile more specific methods of this class?

Thanks for your help

**Comment by SamSaffron** [comment]
> My first question is: being 943 the amount of total retained objects this actually means that i have a memory leak?  

Not necessarily, you would need to look at the particular objects or use a technique like this https://samsaffron.com/archive/2015/03/31/debugging-memory-leaks-in-ruby to determine for sure. 

>The line 1 of person.rb is the declaration of the class, specifically 

Probably just that the class definition when first evaluated caused a large memory allocation, which is common with AR

**Comment by mariosouto** [comment]
@SamSaffron Ok, thanks for your help! 💯
