### ISSUE TITLE
Option to normalize filepaths

### ISSUE THREAD

**Issue by will89** [SamSaffron/memory_profiler#64]
First off, this gem rules! Is there any way for 'normalizing' a path to the file? I'm hoping to find a way to make these reports more shareable between developers with an end goal of maybe even checking these memory reports into version control to check for performance regressions. With the report containing machine dependent filepaths like `/home/sam/.rbenv/versions/2.1.0-github/` or `/Users/will/.rvm/gems/ruby-2.5.1/gems/` would generate a lot of noise in diffs.

For example,
```
/home/sam/.rbenv/versions/2.1.0-github/lib/ruby/gems/2.1.0/gems/mime-types-2.0/lib/mime/type.rb x 3391763
/home/sam/.rbenv/versions/2.1.0-github/lib/ruby/2.1.0/json/common.rb x 2021853
/home/sam/.rbenv/versions/2.1.0-github/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb x 285433
```

Could be normalized to something like the following (Warning: not entirely sure what part from the filepaths above are environment dependent vs not):

```
mime-types-2.0/lib/mime/type.rb x 3391763
json/common.rb x 2021853
core_ext/kernel_require.rb x 285433
```

**Comment by SamSaffron** [comment]
I like, as an option, default off I totally support it.
