### ISSUE TITLE
Showing only application specific results

### ISSUE THREAD

**Issue by milani** [SamSaffron/memory_profiler#66]
Currently, the reports are mostly populated by gems that are used in the code. Having an option to suppress them would be awesome. Then one can focus on how his/her code is doing.

**Comment by schneems** [comment]
You can manually ignore files https://github.com/SamSaffron/memory_profiler/pull/7

However, it might be easier to go the other way and use the ability to instead focus on files.

**Comment by erwanlr** [comment]
The `allow_files` option of the #report is what you are looking for ^^

**Comment by milani** [comment]
Thank you. So I close the issue.
