### ISSUE TITLE
Release of new version with scale_bytes ?

### ISSUE THREAD

**Issue by erwanlr** [SamSaffron/memory_profiler#68]
The Readme mentions a ```scale_bytes``` option. However, it is not available in the latest stable 0.9.12 version. Got me confused as I though the version was not working.

Is there any ETA for the release of a new version with this option ?

**Comment by SamSaffron** [comment]
Sorry for the delay ... I just pushed 0.9.13 with the new option, thanks for reminding me.

**Comment by erwanlr** [comment]
Awesome, thank you!
