### ISSUE TITLE
ObjectSpace.dump_all diff based profiling

### ISSUE THREAD

**Issue by casperisfine** [SamSaffron/memory_profiler#88]
👋 @SamSaffron, it's super early so I don't really have much code to show, but I've been playing with an idea since this morning.

### Context

In MRI there was many objects that are hidden to `ObjectSpace.each_object`, that include many internal objects such as `IMEMO`, instruction sequences, etc, as well as regular objects hidden with `rb_obj_hide` because they are literal constants etc.

On our app, I'm running `memory_profiler` around the entire boot, and it reports a total of ~600MB. However in parallel (another CI job) I also call `ObjectSpace.dump_all` for analysis with [harb](https://github.com/csfrancis/harb), and a simple:

```bash
$ jq 'if .memsize == null then 0 else .memsize end' dumps/shopify-production-boot-heap-2020-07-09.dump | awk '{ sum += $1 } END { print sum }'
885314785 # 844MB
```

So in our case, a good third of the ruby heap is invisible to memory profiler.

### Idea

So I think memory profiler could do the following:

```ruby
GC.start && GC.disable
dump_the_heap '/tmp/pre-heap.json'
run_the_snippet
dump_the_heap '/tmp/post-run-heap.json'
GC.enable && GC.start
dump_the_heap '/tmp/post-gc-heap.json'

allocated = "post-run-heap" - "pre-heap"
retained =  "post-gc-heap" - "pre-heap"
```

One big challenge though is that we'd need to parse the heap files several times, and it's not that fast. The `jq` above takes `52s` on my machine to parse that `1.6GB` file. However using `simdjson`, I'm able to get the same result in `13s`:

```ruby
require 'fast_jsonparser'
memsize = 0
FastJsonparser.load_many(ARGV.first, batch_size: 33_554_432) do |object|
  memsize += object[:memsize].to_i
end
p memsize
```

The same thing using stdlib's `json` is `42s`. So it would be possible to use `fast_jsonparser` if available, and otherwise fallback to the stdlib.

### Required data

The heap dump contains:

  - `memsize`, same value as `ObjectSpace.memsize_of`.
  - string values (unless they're very big), so the String Report could be implemented.
  - the `class`, even though it's an address pointer, so we'd need to build a map of class names.
  - `file` and `line` for the allocation source.

So unless I'm missing something, there's all the data needed.

It might also even help with https://github.com/SamSaffron/memory_profiler/issues/78

### so?

So I wonder if you'd be interested in such change. It would almost be rewrite, so I'd rather check with you first if you are open to it of if I should instead create a new gem. Let me know.

**Comment by schneems** [comment]
If you're interested in adding heap diffing, I would love to add support for it to heapy: https://github.com/schneems/heapy

**Comment by casperisfine** [comment]
Hum, I'm not really a user of heapy, but now that you mention it, this could actually be done purely out of band by heapy (with some new features).

With the 3 `ObjectSpace.dump_all` mentioned, followed by some number crunching. e.g.

```ruby
Heapy.report('some/directory') do
  # your code
end
```

And then you get:

  - `some/directory/base.heap`
  - `some/directory/allocations.heap`
  - `some/directory/retained.heap`

And can do something like `heapy report some/directory` and get a report similar to the MemoryProfiler full report.

You'd you be open to such PR?

**Comment by schneems** [comment]
> You'd you be open to such PR?

Totally. I can also give you commit access to the repo as well if you're interested.

**Comment by casperisfine** [comment]
I'll play with heapy tomorrow, see what I can come up with.

**Comment by SamSaffron** [comment]
I love the idea of making this technique more accessible, improving heapy sounds like a great path forward here. 

Diff based profiling is really powerful, also mwrap needs more airtime, it finds stuff that can be hidden from heap dumps https://samsaffron.com/archive/2019/10/08/debugging-unmanaged-and-hidden-memory-leaks-in-ruby

@schneems one thing we can do right away is add some useful links to the README here, care to do a PR linking at least to heapy and explaining why you would use it?

**Comment by casperisfine** [comment]
Hum. So I'm sorry to report that a good part of Heapy just can't work on 2.7. The entire `Heapy::Alive` section rely on `object_id` being the `address` dumped in the json heap, and that's no longer true in 2.7 (object_id is now a lazy incremental id assigned when accessed).

So there's only the heap analysis part that's left. Given that I think I'll start fresh, I'll report back when I have something functional to show and we'll see if it's worth merging somewhere or if it's better on its own.

**Comment by schneems** [comment]
If you look at the docs `Heapy::Alive` is experimental. I tried doing a similar thing with https://github.com/schneems/living_dead and frankly neither worked. It can be deleted from the codebase safely.

**Comment by casperisfine** [comment]
Oh I didn't see that. Well now I got https://github.com/Shopify/heap-profiler. It's still missing the String reporting, as well as an optimization pass. But apart from that it's functionally equivalent to MemoryProfiler.

**Comment by casperisfine** [comment]
Closing this since https://github.com/Shopify/heap-profiler now does what was required. 

I did steal some code from `memory_profiler` so thanks @SamSaffron!

**Comment by ioquatix** [comment]
I discussed this briefly with @ko1 and he said it might be possible to calculate retained objects from a single heap dump. Maybe worth considering.

**Comment by byroot** [comment]
@ioquatix Could you elaborate? Are you suggesting to rebuild the dependency graph to detect objects that can be freed?

What I had in mind to make the heap dumping faster was to add a `generation` parameter to `dump_all` so that we can only dump the parts of the heap we care about.

**Comment by ioquatix** [comment]
Yes, I think you are on the right path with both your points. I also thought it would be easier if you could dump the generation number, and whether the object was retained.
