### ISSUE TITLE
Feature request: CLI for quick and dirty memory profiling

### ISSUE THREAD

**Issue by fatkodima** [SamSaffron/memory_profiler#90]
Would you be open for such a cli?

Something like
`$ memory-profiler script.rb ..options..` 

instead of code modifications and writing required wrapping code.

**Comment by SamSaffron** [comment]
sounds great! only concern I have is what we name this thing. 

Maybe `ruby_memory_profiler` or `ruby-memory-profiler` I worry that `memory-profiler` is a bit generic and may clash naming wise with other tools.
