### ISSUE TITLE
retained memory (maybe) reports released objects

### ISSUE THREAD

**Issue by senhalil** [SamSaffron/memory_profiler#96]
I am debugging an application for high memory usage and came across to something weird :confused:  I am not 100% sure if it is a bug but our expectations and tests point to that direction.

```ruby
report = MemoryProfiler.report(top: 10) do
  # some method
end
report.pretty_print
```
reports
```
Total allocated: 491959315 bytes (337088 objects)
Total retained:  150970508 bytes (7106 objects)

allocated memory by gem
-----------------------------------
 147231872  active_hash-ed1faced2e4a
  84880339  activesupport-5.2.3
  84054872  rest-client-2.0.2
  68179352  json-2.2.0
  59272721  optimizer-api/lib     
  26251503  socket
  21429171  net
    303143  uri
    280025  other
     58593  http-cookie-1.0.3
...
retained memory by gem
-----------------------------------
  71562722  rest-client-2.0.2       (* we can't explain this since the variables are long gone)
  59166800  optimizer-api/lib
  20165388  net                     (* neither this)
     42321  uri
     15085  activesupport-5.2.3
      9893  other
      7179  http-cookie-1.0.3
       424  redis-3.3.5
       312  active_hash-ed1faced2e4a
       264  multi_json-1.13.1
```
while
```ruby
HeapProfiler.report('./') do
  # the same method
end
```
reports (which agrees with what we expected)
```
Total allocated: 552.43 MB (347935 objects)
Total retained: 59.29 MB (4713 objects)

allocated memory by gem
-----------------------------------
 147.23 MB  active_hash-ed1faced2e4a
 132.07 MB  activesupport-5.2.3
  96.41 MB  rest-client-2.0.2
  68.18 MB  json-2.2.0
  59.27 MB  optimizer-api/lib
  27.46 MB  socket
  20.96 MB  net
 330.77 kB  other
...
retained memory by gem
-----------------------------------
  59.17 MB  optimizer-api/lib
  41.19 kB  rest-client-2.0.2
  31.74 kB  http-cookie-1.0.3
  26.26 kB  activesupport-5.2.3
  19.17 kB  other
```
plus if we call `GC` inside the MemoryProfiler report block -- of course the allocated only reports the retained objects as expected but also -- the unexpected entries of the retained list disappears. 

```ruby
report = MemoryProfiler.report(top: 10) do
  # the same method
  GC.enable
  4.times { GC.start }
end
report.pretty_print
```
reports
```
Total allocated: 59323368 bytes (6062 objects) 
Total retained:  59226928 bytes (4093 objects)

allocated memory by gem
-----------------------------------
  59166800  optimizer-api/lib
    102138  other
     34785  rest-client-2.0.2
     12664  activesupport-5.2.3
      6669  http-cookie-1.0.3
       312  active_hash-ed1faced2e4a
...
retained memory by gem
-----------------------------------
  59166800  optimizer-api/lib
     34313  rest-client-2.0.2
     12664  activesupport-5.2.3
      6669  http-cookie-1.0.3
      6170  other
       312  active_hash-ed1faced2e4a
```
I can't understand how calling the `GC` inside the block can change the retained memory since `MemoryProfiler.stop` method calls `GC` as well. I check the beginning of the  `MemoryProfiler.stop` method with no luck to see if there is something that would lead to objects being retained  ¯\_(ツ)_/¯

Would appreciate your input about the observations above and if this is a memory-profiler bug or not.

Happy holiday season and a happy new year!

**Comment by SamSaffron** [comment]
Sounds super odd give we call it 3 times here. 

https://github.com/SamSaffron/memory_profiler/blob/master/lib/memory_profiler/reporter.rb#L52-L54

GC.start is not deterministic, it can still leave some object behind, maybe we add an `aggressive: ` mode which calls GC.start more times, or watches for "decrease" in total objects and only stops calling when the number stops going down.

What version of Ruby are you on? Can you fiddle with the source of mem profiler to see if there is a hack that can resolve your issue? 

Happy holidays.

**Comment by senhalil** [comment]
I am on Ruby 2.5.5 (ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux])

I did fiddle a fair bit and compared it to that of heap-profiler and increased the number of GC operations, change their order etc with no avail.

Except the fact that heap-profiler uses `ObjectSpace.dump_all` I didn't see much difference. But the source of the diff might be in another file, I didn't go beyond reporter.rb and heap-profiler delegates the comparison and analysis of allocated-vs-retained memory to another routine.

**Comment by senhalil** [comment]
Eureka! Until now I apparently haven't tried with `times` block. (This was one of the differences between heap-profiler which I didn't check :facepalm: never-ignore-any-difference-even-if-it-is-small :sob:)  If I replace the repeated GC.start calls with a times block it consistently works! 

I don't know what's special about using a block :thinking: context? In my original tests even the following code worked:  
```ruby
report = MemoryProfiler.report(top: 10) do
  # the same method
  GC.enable
  GC.start
end
report.pretty_print
```
so block or repetition was not needed for correct behavior.

Anyhow, I prepared a PR and replaced the GC.start calls if it's okay for you, since this fixed completely the issue I observed, I suggest closing this ticket with that PR but I agree that an intelligent `aggressive` mode would make a very good addition.
